runtime: nodejs20
env: standard
beta_settings:
  cloud_sql_instances: "send-social-starter-kit:us-central1:send-social-kit"
env_variables:
  NODE_ENV: "production"
  WALLET_PRIVATE_KEY: "4zHGnAKMgC4zniPURoAyxSJY36d1WcDJreRHL43KN4mxGNnVtPHjn7Bu64xEFKpGxx5SAYBxnwxTEdwsEFAsbFk4"
  RPC_URL: "https://devnet.helius-rpc.com/?api-key:e1a9b81d-bda1-46df-be73-7a4659c9a7ec"
  TOKEN_MILL_PROGRAMID: "JoeaRXgtME3jAoz5WuFXGEndfv4NPH9nBxsLq44hk9J"
  TOKEN_MILL_CONFIG_PDA: "5LZxxqYVZNKK8GnY5Ye4DRptU1gKP1xp4mJTujzg2LpY"
  SWAP_AUTHORITY_KEY: "4zHGnAKMgC4zniPURoAyxSJY36d1WcDJreRHL43KN4mxGNnVtPHjn7Bu64xEFKpGxx5SAYBxnwxTEdwsEFAsbFk4"
  PINATA_JWT: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJmMmMyNzJlYS1lYTBlLTRhYzMtYmE5MC02ODZhOWVjNDA2YTIiLCJlbWFpbCI6ImJodXdhbnR5YWdpMjAwMEBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiNjQ3Mzk3ODYwMzMyNDUzZjBkNzAiLCJzY29wZWRLZXlTZWNyZXQiOiIxODc0MjQzMGEyNGI5YjFlZWM4MzZkZDMxYTY5ZjBmYjNjNzFkNDg4OWJmOTlmYjkyMmU0YTE4ZTliMGJjOGQwIiwiZXhwIjoxNzcxNjUxNTQ4fQ.N8pgn4WRX1VkA4E8nGA0g6WRffEIRpdk0oj6iwxeuMY"
  PINATA_GATEWAY: "jade-perfect-wombat-217.mypinata.cloud"
  PINATA_SECRET: "18742430a24b9b1eec836dd31a69f0fb3c71d4889bf99fb922e4a18e9b0bc8d0"
  PINATA_API_KEY: "647397860332453f0d70"
  DATABASE_URL: "postgresql://postgres:Send_69@/postgres?host=/cloudsql/send-social-starter-kit:us-central1:send-social-kit"
  GCS_BUCKET_NAME: "send-social-starter-bucket"
  SERVICE_ACCOUNT_EMAIL: "send-social-bucket-uploader@send-social-starter-kit.iam.gserviceaccount.com"
  INSTANCE_CONNECTION_NAME: "send-social-starter-kit:us-central1:send-social-kit"
  DB_USER: "postgres"
  DB_PASS: "Send_69"
  DB_NAME: "postgres"